### ISSUE TITLE
net::ERR_CACHE_MISS on long pressing for web searches

### ISSUE THREAD

**Issue by ensvo** [CaptainDario/DaKanjiRecognizer-Mobile#2]
Currently hitting an error screen when long pressing to search on all web options. This is what is displayed when I tested a search for 前 with jisho(web) settings, for instance.

> Web page not available
The web page at https://jisho.org/search/%E5%89%8D could not be loaded because:
net::ERR_CACHE_MISS

Using a Google Pixel 4 on Android 11, if that helps!

System Translator and Takoboto long press searches work completely fine and I'll be sticking with those for now. I've been waiting so long for an app like this and excited to see it grow! :)

**Comment by CaptainDario** [comment]
Thank you for the details they helped figuring this out.
I used a different android version and there it was somehow working.

A new build should be available in the play store in a few minutes/hours.
It would be great if you could report here if everything is working for you with this release.

**Comment by ensvo** [comment]
All web searches work perfectly now. Thanks for taking the time to fix it!

**Comment by CaptainDario** [comment]
Thanks for reporting!
